stages:
 - test

tests_basic:
  stage: test
  except:
    - tags
  image: registry.gitlab.com/thgnet/docker-centos7wre:v2
  variables:
    RUNTIME_TYPE: development
    RUNTIME_VERSION: php72
    RUNTIME_EXTENSIONS: xdebug
  script:
   - tests/run_static_checks.sh
   - tests/run_tests.sh all
  cache:
    key:
      files:
       - tests/run_static_checks.sh
    paths:
      - .local.tools

tests_php_versions:
  stage: test
  needs: [ "tests_basic" ]
  except:
    - tags
  image: registry.gitlab.com/thgnet/docker-centos7wre:v2
  variables:
    RUNTIME_TYPE: development
  parallel:
    matrix:
      - RUNTIME_VERSION: php53
      - RUNTIME_VERSION: php56
      - RUNTIME_VERSION: php72
      - RUNTIME_VERSION: php74
      - RUNTIME_VERSION: php80
      - RUNTIME_VERSION: php81
      - RUNTIME_VERSION: php82
  script:
   - tests/run_tests.sh php
